# Generated by Django 5.2.9 on 2025-12-28 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='submitted_for_verification',
            field=models.BooleanField(default=False),
        ),
    ]
