# Generated by Django 5.2.9 on 2025-12-12 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_category_tag_post_comment_like'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_at'], 'verbose_name': 'comment', 'verbose_name_plural': 'comments'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at'], 'permissions': [('can_verify_post', 'Can verify post')], 'verbose_name': 'post', 'verbose_name_plural': 'posts'},
        ),
    ]
